import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { useEffect, useState } from "react";
import Head from "next/head";
import CssBaseline from "@mui/material/CssBaseline";
import authUtils from "../utils/authUtils";
import { useRouter } from "next/router";
import Loading from "../components/Loading";

const AuthLayout = ({ children }) => {
  const router = useRouter();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const checkAuth = async () => {
      const isAuth = await authUtils.isAuthenticated();

      if (!isAuth) {
        setLoading(false);
      } else {
        router.push("/");
      }
    };

    checkAuth();
  }, [router]);

  return loading ? (
    <Loading fullHeight />
  ) : (
    <>
      <CssBaseline />
      <Head>
        <title>Kanban App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
};

export default AuthLayout;
